# Generated by Django 5.0.2 on 2024-02-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='one_to_many_relation',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='heading',
            new_name='title',
        ),
    ]
