# Generated by Django 5.0.2 on 2024-04-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='many_to_many_relation',
            new_name='category',
        ),
    ]
