# Generated by Django 5.0.2 on 2024-02-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_one_to_many_relation_post_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='one_to_many_relation',
            new_name='comment_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='one_to_many_relation1',
            new_name='comment_user',
        ),
    ]
